export const SAMPLE_EVENT_DATA = [
  {
    Date: "2024-02-16",
    Time: "10:35:00",
    "Time Zone": "America/Toronto",
    Category: "Frostbite Cup",
    Item: "Classic Hoodie",
    Qty: 3,
    "Price Point Name": "Black",
    SKU: "HOOD-BLK-4XL",
    "Modifiers Applied": "Adult 4XL",
    "Gross Sales": 225,
    Discounts: 0,
    "Net Sales": 225,
    Tax: 0
  },
  {
    Date: "2024-02-16",
    Time: "12:10:00",
    "Time Zone": "America/Toronto",
    Category: "Frostbite Cup",
    Item: "Classic Hoodie",
    Qty: 14,
    "Price Point Name": "Black",
    SKU: "HOOD-BLK-XL",
    "Modifiers Applied": "Adult XL",
    "Gross Sales": 1050,
    Discounts: 0,
    "Net Sales": 1050,
    Tax: 0
  },
  {
    Date: "2024-02-16",
    Time: "13:20:00",
    "Time Zone": "America/Toronto",
    Category: "Frostbite Cup",
    Item: "Classic Hoodie",
    Qty: 20,
    "Price Point Name": "Navy",
    SKU: "HOOD-NV-L",
    "Modifiers Applied": "Adult L",
    "Gross Sales": 1500,
    Discounts: 0,
    "Net Sales": 1500,
    Tax: 0
  },
  {
    Date: "2024-02-16",
    Time: "14:10:00",
    "Time Zone": "America/Toronto",
    Category: "Frostbite Cup",
    Item: "Classic Shirt",
    Qty: 18,
    "Price Point Name": "White",
    SKU: "SHRT-WHT-M",
    "Modifiers Applied": "Adult M",
    "Gross Sales": 450,
    Discounts: 0,
    "Net Sales": 450,
    Tax: 0
  },
  {
    Date: "2024-02-16",
    Time: "15:05:00",
    "Time Zone": "America/Toronto",
    Category: "Frostbite Cup",
    Item: "Classic Shirt",
    Qty: 9,
    "Price Point Name": "White",
    SKU: "SHRT-WHT-YL",
    "Modifiers Applied": "Youth Large",
    "Gross Sales": 225,
    Discounts: 0,
    "Net Sales": 225,
    Tax: 0
  },
  {
    Date: "2024-02-16",
    Time: "15:35:00",
    "Time Zone": "America/Toronto",
    Category: "Frostbite Cup",
    Item: "Add-On $5",
    Qty: 18,
    "Gross Sales": 90,
    Discounts: 0,
    "Net Sales": 90,
    Tax: 0
  },
  {
    Date: "2024-02-16",
    Time: "15:40:00",
    "Time Zone": "America/Toronto",
    Category: "Frostbite Cup",
    Item: "Add-On $10",
    Qty: 7,
    "Gross Sales": 70,
    Discounts: 0,
    "Net Sales": 70,
    Tax: 0
  },
  {
    Date: "2024-03-09",
    Time: "09:40:00",
    "Time Zone": "America/Toronto",
    Category: "Rinkside Classic",
    Item: "Classic Hoodie",
    Qty: 6,
    "Price Point Name": "Black",
    SKU: "HOOD-BLK-2XL",
    "Modifiers Applied": "Adult 2XL",
    "Gross Sales": 450,
    Discounts: 0,
    "Net Sales": 450,
    Tax: 0
  },
  {
    Date: "2024-03-09",
    Time: "10:15:00",
    "Time Zone": "America/Toronto",
    Category: "Rinkside Classic",
    Item: "Classic Hoodie",
    Qty: 12,
    "Price Point Name": "Grey",
    SKU: "HOOD-GRY-L",
    "Modifiers Applied": "Adult L",
    "Gross Sales": 900,
    Discounts: 0,
    "Net Sales": 900,
    Tax: 0
  },
  {
    Date: "2024-03-09",
    Time: "11:25:00",
    "Time Zone": "America/Toronto",
    Category: "Rinkside Classic",
    Item: "Classic Shirt",
    Qty: 10,
    "Price Point Name": "Grey",
    SKU: "SHRT-GRY-S",
    "Modifiers Applied": "Adult Small",
    "Gross Sales": 250,
    Discounts: 0,
    "Net Sales": 250,
    Tax: 0
  },
  {
    Date: "2024-03-09",
    Time: "12:05:00",
    "Time Zone": "America/Toronto",
    Category: "Rinkside Classic",
    Item: "Classic Shirt",
    Qty: 8,
    "Price Point Name": "Grey",
    SKU: "SHRT-GRY-YM",
    "Modifiers Applied": "Youth Medium",
    "Gross Sales": 200,
    Discounts: 0,
    "Net Sales": 200,
    Tax: 0
  },
  {
    Date: "2024-03-09",
    Time: "12:20:00",
    "Time Zone": "America/Toronto",
    Category: "Rinkside Classic",
    Item: "Add-On $5",
    Qty: 9,
    "Gross Sales": 45,
    Discounts: 0,
    "Net Sales": 45,
    Tax: 0
  },
  {
    Date: "2024-03-09",
    Time: "12:25:00",
    "Time Zone": "America/Toronto",
    Category: "Rinkside Classic",
    Item: "Add-On $10",
    Qty: 3,
    "Gross Sales": 30,
    Discounts: 0,
    "Net Sales": 30,
    Tax: 0
  }
];
